### ISSUE TITLE
Unable to add a Hawkular provider due to Angularization

### ISSUE THREAD

**Issue by tumido** [ManageIQ/manageiq-providers-hawkular#97] opened 2017-11-03 14:39 UTC
I don't know when it happened exactly, but I'm currently unable to add a Hawkular provider into ManageIQ with current master. It's caused by the change in use of `verify_credentials` (it seems it's no longer used). The current workflow is using a `create_ems_button_validate` (defined [here](https://github.com/ManageIQ/manageiq-ui-classic/blob/0697177b8393f42237705aebf97e159b93f1215b/app/controllers/mixins/ems_common_angular.rb#L81)) which calls `raw_connect` and uses `get_task_args` ([here](https://github.com/ManageIQ/manageiq-ui-classic/blob/0697177b8393f42237705aebf97e159b93f1215b/app/controllers/mixins/ems_common_angular.rb#L116)) mapping to get proper arguments.

I'll form a PR adding mapping for Hawkular into `get_task_args`, if the issue is confirmed.

**Comment by tumido** [comment] 2017-11-03 14:39
cc @karelhala, @abonas

**Comment by tumido** [comment] 2017-11-03 14:52
We might also consider investigation if the `validate_credentials` is ever needed and used.

**Comment by tumido** [comment] 2017-11-03 15:12
The workflow which used to work was:
- MIQ calls our `validate_credentials`
- `validate_credentials` calls `connect`
- `connect` parses arguments needed for `raw_connect` and calls it
- done

Current workflow which I discovered:
- MIQ tries to parse arguments for `raw_connect` via mapping in `get_task_args`
- then it places a job to MiqQueue which calls `raw_connect`

And we're missing the mapping now...

**Comment by abonas** [comment] 2017-11-05 11:05
is this a duplicate of [this](https://github.com/ManageIQ/manageiq-ui-classic/issues/2572)?

**Comment by tumido** [comment] 2017-11-05 11:43
@abonas it seems so. Closing.

**Closed** 2017-11-05 11:44 UTC
Labels: bug
